//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonnement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abonnement()
        {
            this.Client = new HashSet<Client>();
        }
    
        public int IDAbonnement { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public System.TimeSpan HeureDep { get; set; }
        public System.TimeSpan HeureDarr { get; set; }
        public int IDVilleDep { get; set; }
        public int IDVilleDarr { get; set; }
        public int NbrVoulu { get; set; }
        public Nullable<int> nbrAtteint { get; set; }
        public bool Climatisation { get; set; }
        public int IDAutocar { get; set; }
        public int IDSociete { get; set; }
        public string AutoImage { get; set; }
    
        public virtual Autocar Autocar { get; set; }
        public virtual Societe Societe { get; set; }
        public virtual Ville Ville { get; set; }
        public virtual Ville Ville1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Client { get; set; }
    }
}
